name: CI

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes \
            libasound2-dev \
            libpipewire-0.3-dev \
            libssl-dev \
            pkg-config \
            shellcheck
      - name: Complete CI check
        run: make check-ci
